apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: binding-role-pods-and-service
  namespace: default
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: Daniel
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: mydevs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-service