apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume
  labels:
    volume: mysql-volume
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    server: 192.168.39.1
    path: "/exports"