apiVersion: v1
kind: Pod
metadata:
  name: kuard-pod
spec:
  containers:
    - name: kuard-container
      image: gcr.io/kuar-demo/kuard-amd64:blue
      ports:
        - containerPort: 8080
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /healthy
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 2
        periodSeconds: 10
        failureThreshold: 3