apiVersion: v1
kind: Pod
metadata:
  name: kuard-pod-resreq
spec:
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:blue
      name: kuard-pod-resreq
      resources:
        requests:
          cpu: "500m"
          memory: "128Mi"
      livenessProbe:
        httpGet:
          path: /healthy
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 5
        periodSeconds: 10
        failureThreshold: 3
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
