apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-ingress
spec:
  rules:
    - host: web-api-core.example.com
      http:
        paths:
          - path: /weatherforecast
            pathType: Prefix
            backend:
              service:
                name: web-api-core
                port:
                  number: 80