apiVersion: v1
kind: Pod
metadata:
  name: kuard-config
spec:
    containers:
      - image: gcr.io/kuar-demo/kuard-amd64:blue
        name: test-config
        imagePullPolicy: Always
        command:
            - "/kuard"
            - "$(ANOTHER_PARAM)"
        env:
          - name: ANOTHER_PARAM
            valueFrom:
              configMapKeyRef:
                name: kuard-configmap
                key: another-param
          - name: EXTRA_PARAM
            valueFrom:
              configMapKeyRef:
                name: kuard-configmap
                key: extra-param
        volumeMounts:
          - name: config-volume
            mountPath: /config
          - name: kuard-tls
            mountPath: /tls
            readOnly: true
    volumes:
      - name: config-volume
        configMap:
          name: kuard-configmap
      - name: kuard-tls
        secret:
          secretName: kuard-tls
    restartPolicy: Never