apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-job-service
  labels:
    app: cron-net-core
spec:
  schedule: "*/1 * * * *"
  startingDeadlineSeconds: 460
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 30
      template:
        metadata:
          labels:
            app: cron-job-netcorepod
        spec:
          containers:
            - name: job-application
              image: ospereiras2020/job-service:v1.0
          restartPolicy: Never
      backoffLimit: 2