apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
  namespace: vote
spec:
  type: ClusterIP
  ports:
    - port: 5432
      name: db-service
      targetPort: 5432
  selector:
    app: db