apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
  namespace: vote
spec:
  type: NodePort
  ports:
    - port: 5001
      name: result-service
      targetPort: 80
      nodePort: 31001
  selector:
    app: result